title: 行进在旅途中，别忘了带干粮 
description: > # this means to ignore newlines until "baseurl:"
  程序员：一个脑力劳动者社会价值无从体现的职业。
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: ALBERT LI # add your name
author-img: albert-li.jpg # add your photo
about-author: I am a full stack developer focusing on end-end development. Always hungry to keep learning. # add description
twitter: systembug
facebook: albert.lee.739978
github: systembugtj # add your Github handle
linkedin: albert-li-3534468
email: albert_lee@hotmail.com

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag

# Collections for better content organization
collections:
  posts:
    output: true
    permalink: /:title/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "ALBERT LI"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "main"

paginate: 8
paginate_path: "/page/:num"

# Forestry CMS configuration
forestry:
  preview_path: /:title/
  preview_host: https://systembugtj.github.io

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
